# 배열의 생성과 변형

- 자료형

In [2]:
import numpy as np
x = np.array([1,2,3])
x.dtype

dtype('int32')

In [4]:
x = np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [7]:
x = np.array([1,2,3.0])
# 데이터 타입이 동일해야하므로 더 큰 범위인 float로 나온다
x.dtype

dtype('float64')

In [8]:
x = np.array([1,2,3.0] ,dtype = 'float32')
x.dtype

dtype('float32')

### INT와 NAN

In [9]:
np.array([0,1,-1,0]) / np.array([1, 0, 0, 0])

array([  0.,  inf, -inf,  nan])

### Math 함수 그냥 가져오면 됨

In [13]:
np.log(0)
### log(0)은 정의되지 않지? - 무한대 = - inf

-inf

In [17]:
# 무한대로 np.inf 로 가져올 수 있다
np.exp(-np.inf)

0.0

### 배열 생성

In [35]:
# numpy의 기본적인 데이터타입이 float
""" 0을 원소로 하는 어레이 """
a= np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [36]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
c = np.zeros( (2,5), dtype="int")
c

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
np.ones(4)

array([1., 1., 1., 1.])

In [39]:
# b와 같은 모양으로 만들어보자
np.ones_like(b) 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
g = np.empty((4,3))
# 배열을 초기화하는데도 시간이 걸린다. 이 시간을 단축하려면 배열을 생성만 하고 특정한 값으로 초기화를 하지 않는 empty 명령을 사용할 수 있다. empty 명령으로 생성된 배열에는 기존에 메모리에 저장되어 있던 값이 있으므로 배열의 원소의 값을 미리 알 수 없
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
# python의 range와 똑같다
np.arange(20,100,3)

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68,
       71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [55]:
# 0에서부터 100까지 5단계로 나눠라
""" 통계에서 1,2,3,4분위수 구할때 쓰이고
모르는 그래프 그릴 때도 쓰인다 (잘게 증분을 나눠야 하니까 그떄 100단계로 나누는 예)"""
""" x = np.linspace(-5,5,100)
    y = 1 / (1 + np.exp(-x)) ==> Sigmoid 함수
"""
""" quispaced interpolating values """
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [63]:
np.logspace(0.1,1,10)
# 상용로그

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [60]:
np.log(np.logspace(0.1,1,10))

array([0.23025851, 0.46051702, 0.69077553, 0.92103404, 1.15129255,
       1.38155106, 1.61180957, 1.84206807, 2.07232658, 2.30258509])