### 벡터화 연산

In [2]:
import numpy as np
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [3]:
%%time
z = np.zeros_like(x)
print(z)
for i in range(10000):
    z[i] = x[i] + y[i]

[0 0 0 ... 0 0 0]
Wall time: 7 ms


In [4]:
%%time
z = x + y

Wall time: 999 µs


### 논리 연산

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [8]:
a == b

array([False,  True, False,  True])

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [11]:
np.all(a == b)

False

In [12]:
np.all(a == c)

True

In [14]:
np.log(a), np.log10(a)

(array([0.        , 0.69314718, 1.09861229, 1.38629436]),
 array([0.        , 0.30103   , 0.47712125, 0.60205999]))

### 브로드캐스팅 <br>
행렬의 크기가 같지 않을 때 알아서 작은 행렬을 확장해서 큰 배열에 맞춰 연산

In [17]:
x = np.arange(5)
y = np.ones_like(x)
x + y, x + 1

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

### 차원 축소 연산

In [21]:
x = np.array([1,2,3,4])
# argmin, argmax는 최솟값,최댓값의 인덱스를 알려줌
x.min() , x.max(), x.mean(), x.argmax(), x.argmin()

(1, 4, 2.5, 3, 0)

In [23]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [24]:
np.sum(x)

6

In [26]:
""" x축(첫번째 축)을 기준으로 """
np.sum(x, axis=0)

array([3, 3])

In [28]:
""" y축(두번째 축)을 기준으로 """
np.sum(x, axis=1)

array([2, 4])

In [40]:
x = np.linspace(1.0 ,10.0, 30).reshape(5,-1).round(2)
x

array([[ 1.  ,  1.31,  1.62,  1.93,  2.24,  2.55],
       [ 2.86,  3.17,  3.48,  3.79,  4.1 ,  4.41],
       [ 4.72,  5.03,  5.34,  5.66,  5.97,  6.28],
       [ 6.59,  6.9 ,  7.21,  7.52,  7.83,  8.14],
       [ 8.45,  8.76,  9.07,  9.38,  9.69, 10.  ]])

In [46]:
np.sum(x, axis=0) , x.sum(axis=0)

(array([128, 160, 193, 175]), array([128, 160, 193, 175]))

In [47]:
np.sum(x, axis=1) , x.sum(axis=1)

(array([ 10, 316, 330]), array([ 10, 316, 330]))

In [45]:
x = np.array([
    [1,2,3,4],
    [46,99,100,71],
    [81,59,90,100]
])
np.sum(x, axis=0), np.sum(x, axis=1) 

(array([128, 160, 193, 175]), array([ 10, 316, 330]))

### 정렬(Sorting)

In [49]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [50]:
np.sort(a)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [52]:
np.sort(a, axis = 0), np.sort(a, axis = 1)
# 열로 정렬, 행으로 정렬

(array([[ 1,  3,  1,  7],
        [ 2, 12,  5,  9],
        [ 4, 15, 11, 14]]),
 array([[ 3,  4,  5,  7],
        [ 1,  9, 11, 12],
        [ 1,  2, 14, 15]]))

In [54]:
# a 자체는 안 바뀐다
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [57]:
# 얘들은 a가 자체가 바뀐다
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])