In [1]:
import numpy as np

In [2]:
np.random.rand(5)

array([0.51794447, 0.30195025, 0.8765771 , 0.53942103, 0.37680468])

In [5]:
np.random.rand(5)

array([0.21695427, 0.27647714, 0.34331559, 0.86215894, 0.15669967])

### seed값 주기

In [3]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

In [4]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

### 데이터 순서 바꾸기

In [10]:
x = np.arange(10)
np.random.shuffle(x)
x

array([3, 1, 0, 2, 7, 4, 5, 8, 9, 6])

### 데이터 샘플링 (표본선택)
이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것 

In [12]:
# shuffle 명령과 같다. 비복원추출
np.random.choice(5, 5, replace=False)  


array([4, 1, 0, 2, 3])

In [13]:
np.random.choice(5, 5, replace=True)  

array([1, 2, 2, 1, 0])

In [14]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택


array([3, 2, 3, 3, 2, 3, 2, 3, 3, 3])

### 난수 생성

In [23]:
# 0에서 1에서까지 나올 수 있는 확률이 같게끔 하는 것ㅡ
np.random.rand(5)

array([0.42712038, 0.98166833, 0.93926839, 0.25673628, 0.34410734])

In [22]:
# 평균 0, 표준편차 1인 표준정규분포 10개 뽑기
# 각각 점이 나타날 확률이 다르다
""" 정규분포를 표준정규분포를 바꿀 때 z = (X - 평균) / 표준편차 """
np.random.randn(10)

array([ 1.26620742,  1.24446983,  0.80523392,  1.08266673,  0.66324872,
        0.61433843, -0.49462885,  1.62266163,  0.53028485,  0.48833726])

In [25]:
# 0~10 사이의 정수 10개
np.random.randint(10, size=10)


array([5, 4, 4, 9, 8, 4, 5, 7, 5, 3])

In [26]:
# 10~20 사이의 정수 10개
np.random.randint(10, 20, size=10)

array([15, 11, 19, 18, 16, 16, 12, 16, 19, 19])

- 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라




In [82]:
price = 10000 
tmr = price + price * np.random.randn(1) / 100 # 퍼센트니까 100으로 나눠줘야 됨
tmr[0]

9956.851421251175

In [81]:
prices = []
price = 10000
for i in range(250):
    tmp = price * (1 + np.random.randn(1)/100)
    price = tmp[0] # array로 나오니까
    prices.append(price)
prices[:10]

[10088.75673426962,
 10176.11629017062,
 10160.208613422432,
 10156.310269059468,
 10203.572983045948,
 10173.468398812502,
 10255.309818941687,
 10167.870215547058,
 10296.664646353787,
 10194.038809928074]

### 정수 데이터 카운팅

In [85]:
# unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력한다 
# 파이썬의 Set과 같다
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [86]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [87]:
index # 집합의 원소

array(['a', 'b', 'c'], dtype='<U1')

In [90]:
count # 원래 몇개만큼 나왔는지

array([2, 2, 1], dtype=int64)