### 벡터와 벡터의 곱셈  

In [3]:
import numpy as np
x = np.arange(1,4).reshape(3,-1)
y = np.arange(4,7).reshape(3,-1)
x,y

(array([[1],
        [2],
        [3]]),
 array([[4],
        [5],
        [6]]))

In [10]:
x.shape, y.shape

((3, 1), (3, 1))

In [13]:
x.T @ y , y.T @ x, (y.T @ x).shape 

(array([[32]]), array([[32]]), (1, 1))

In [14]:
np.dot(x.T, y)

array([[32]])

In [17]:
x = np.arange(1,7).reshape(2,-1)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
x.T @ x , x @ x.T

(array([[17, 22, 27],
        [22, 29, 36],
        [27, 36, 45]]),
 array([[14, 32],
        [32, 77]]))

In [25]:
inner_prod([[1,2],[3,4]] , [[1,2],[3,4]])

100

In [26]:
x = np.array([[1,2],[3,4]])
x @ x

array([[ 7, 10],
       [15, 22]])

In [37]:
price = np.array([100,80,50])
num = np.array([3,4,5])

In [38]:
price.T @ num

870

In [40]:
A = np.array([1,2,3,4,5,6]).reshape(2,-1)
B = np.array([1,2,3,4,5,6]).reshape(3,-1)
A,B

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [41]:
A @ B

array([[22, 28],
       [49, 64]])

In [42]:
B @ A

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [45]:
A = np.array([1,2,3])
B = np.array([4,5,6,7,8,9]).reshape(2,-1)
A, B

(array([1, 2, 3]),
 array([[4, 5, 6],
        [7, 8, 9]]))