In [4]:
import numpy as np
# 길이가 10인 0벡터
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
# 길이가 10인데 다섯번째 원소만 1이고 나머지 원소는 0
np.eye(1, 10, k = 4 , dtype=np.int8)[0]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

In [22]:
# 10부터 49까지 값을 가지는 벡터
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [28]:
# Descending order
np.sort(x)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
# 0부터 8까지 3x3
A = np.arange(9).reshape(3,-1)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# 0 아닌 원소만
x = np.array([1,2,0,0,4,0])
x[x != 0]

array([1, 2, 4])

In [13]:
# 단위행렬
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# 난수행렬 3x3
A = np.random.rand(9).reshape(3,-1)
A

array([[0.04237847, 0.03564127, 0.98412258],
       [0.22440564, 0.64125834, 0.86047206],
       [0.71147057, 0.81465189, 0.64612922]])

In [16]:
# 전체 원소 최소/최대값
A.min(), A.max()

(0.03564127343922996, 0.9841225816071857)

In [19]:
# 행 평균
A.mean(axis=0) 

array([0.32608489, 0.49718383, 0.83024129])

In [29]:
# 열 평균
A.mean(axis=1)

array([0.35404744, 0.57537868, 0.72408389])